Several changes to postgres

diff --git a/postgresql/files/run_psql b/postgresql/files/run_psql
--- a/postgresql/files/run_psql
+++ b/postgresql/files/run_psql
@@ -1,3 +1,8 @@
 #!/bin/sh
 
-exec /usr/bin/psql -h postgresql.service.local -d template1 -U dbadmin
+if [[ -z "${POSTGRESQL_HOST}" ]]; then
+  echo "[E] POSTGRESQL_HOST not set, cannot connect"
+  exit 1
+fi
+
+exec /usr/bin/psql -h ${POSTGRESQL_HOST} -d template1 -U dbadmin
